version: '3.8'

services:
  nginx:
    image: nginx:latest

    ports:
      - "443:443"
      - "80:80"

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - ./cert:/etc/ssl/cert